#!/usr/bin/env bash
# This script will show you if a host is on the network.

# Check if the user has provided an argument
if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <hostname>"
  exit 1
fi

# Check if the host is reachable
IP_ADDRESS=$1

# Ping the host
ping -c 5 "$IP_ADDRESS"
