#!/usr/bin/env bash
# Configures the network interface with a new IP address

# Backup
sudo cp /etc/hosts /etc/hosts.bak

# Remove localhost
sudo sed -i '/127.0.0.1/s*localhost/d' /etc/hosts
sudo sed -i '/facebook.com/d' /etc/hosts

# Add new IP
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null

echo "Host resolution updated: localhost -> 127.0.0.2, facebook.com -> 8.8.8.8"
